openapi: 3.0.0
info:
  title: TEN API Documentation
  version: 1.0.0
  description: API documentation for The Experiences Network (TEN)
  contact:
    name: API Support
    url: https://docs.ten.network/support
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: '{protocol}://{host}:{port}'
    variables:
      protocol:
        enum:
          - http
          - https
        default: http
      host:
        default: localhost
      port:
        default: '3000'

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: connect.sid
  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
          description: Error message
        code:
          type: string
          description: Error code
        status:
          type: integer
          description: HTTP status code
    User:
      type: object
      properties:
        id:
          type: integer
          description: User ID
        username:
          type: string
          description: Username
      required:
        - id
        - username

tags:
  - name: Auth
    description: Authentication endpoints
  - name: User
    description: User management endpoints
  - name: Health
    description: Health check endpoints

paths:
  /health:
    get:
      tags:
        - Health
      summary: Health check endpoint
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
